version: "3"
services:
  db:
    image: postgres:12.5
    container_name: postgres-test
    networks:
      - backend
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - DB_HOST=dbhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - "5434:5432"
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    ports:
      - 3310:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=akbarov.dev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
    networks:
      - backend
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  backend:

volumes:
  pgadmin-data:
